"""Add Zone model and link to Camera

Revision ID: 04628801f933
Revises: 814982343356
Create Date: 2025-07-11 01:54:27.355240

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04628801f933'
down_revision: Union[str, Sequence[str], None] = '814982343356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

bind = op.get_bind()
inspector = inspect(bind)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'zones' not in inspector.get_table_names():
        op.create_table('zones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.add_column('cameras', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    with op.batch_alter_table('cameras') as batch_op:
        batch_op.create_foreign_key('fk_cameras_zone_id', 'zones', ['zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_column('cameras', 'zone_id')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
